### PR TITLE
Fixes to SQL ordinals

### LINKED ISSUE #5948: Error "no corresponding grouping element for non-aggregate" with ClickBench q34
## tl;dr

The [ClickBench q34 SQL](https://github.com/ClickHouse/ClickBench/blob/351f77f5e1ca34b292a745928dfeef5e4a86a8f3/clickhouse/queries.sql#L35) is currently rejected by SuperDB though it was previously accepted and would produce the correct result in the past.

```
$ super -version
Version: 6833db0f5

$ SUPER_VAM=1 super -c "
SELECT 1,
       URL,
       COUNT(*) AS c
FROM 'data.parquet'
GROUP BY 1,
         URL
ORDER BY c DESC
LIMIT 10;"
no corresponding grouping element for non-aggregate "1" at line 2, column 8:
SELECT 1,
       ~
```

## Details

Repro is with super commit 6833db0 (which is associated with the changes in #5938) and the attached [data.parquet.gz](https://github.com/user-attachments/files/20660945/data.parquet.gz), which is a small subset of the overall ClickBench test data.

At the commit that came right before the merge of #5938, this query ran fine.

```
$ SUPER_VAM=1 super -c "
SELECT 1,
       URL,
       COUNT(*) AS c
FROM 'data.parquet'
GROUP BY 1,
         URL
ORDER BY c DESC
LIMIT 10;"

{"1":1,URL:null(string),c:5(uint64)}
{"1":1,URL:"http://bonprix.ru/index.ru/cinema/art/0 986 424 233 сезон",c:1(uint64)}
{"1":1,URL:"http://bonprix.ru/index.ru/cinema/art/A00387,3797); ru)&bL",c:1(uint64)}
{"1":1,URL:"http://tours/Ekategoriya%2F&sr=http://slovareniye",c:1(uint64)}
{"1":1,URL:"http://afisha.mail.ru/catalog/314/women.ru/ency=1&page3/?errovat-pinniki",c:1(uint64)}
{"1":1,URL:"http://holodilnik.ru/russia/05jul2013&model=0",c:1(uint64)}
```

Other SQL systems like ClickHouse and DuckDB accept this SQL without complaint.

```
$ clickhouse --version
ClickHouse local version 25.5.2.47 (official build).

$ clickhouse --query "
SELECT 1,
       URL,
       COUNT(*) AS c
FROM 'data.parquet'
GROUP BY 1,
         URL
ORDER BY c DESC
LIMIT 10;"

1	\N	5
1	http://bonprix.ru/index.ru/cinema/art/A00387,3797); ru)&bL	1
1	http://holodilnik.ru/russia/05jul2013&model=0	1
1	http://bonprix.ru/index.ru/cinema/art/0 986 424 233 сезон	1
1	http://tours/Ekategoriya%2F&sr=http://slovareniye	1
1	http://afisha.mail.ru/catalog/314/women.ru/ency=1&page3/?errovat-pinniki	1

$ duckdb --version
v1.3.0 71c5c07cdd

$ duckdb -c "
SELECT 1,
       URL,
       COUNT(*) AS c
FROM 'data.parquet'
GROUP BY 1,
         URL
ORDER BY c DESC
LIMIT 10;"

┌───────┬──────────────────────────────────────────────────────────────────────────┬───────┐
│   1   │                                   URL                                    │   c   │
│ int32 │                                 varchar                                  │ int64 │
├───────┼──────────────────────────────────────────────────────────────────────────┼───────┤
│     1 │ NULL                                                                     │     5 │
│     1 │ http://afisha.mail.ru/catalog/314/women.ru/ency=1&page3/?errovat-pinniki │     1 │
│     1 │ http://bonprix.ru/index.ru/cinema/art/0 986 424 233 сезон                │     1 │
│     1 │ http://bonprix.ru/index.ru/cinema/art/A00387,3797); ru)&bL               │     1 │
│     1 │ http://tours/Ekategoriya%2F&sr=http://slovareniye                        │     1 │
│     1 │ http://holodilnik.ru/russia/05jul2013&model=0                            │     1 │
└───────┴──────────────────────────────────────────────────────────────────────────┴───────┘
```

### LINKED ISSUE #5975: SQL: Referring to the same alias twice
Repro is with super commit 9449896. This was found via a query from [a sqllogictest](https://github.com/duckdb/duckdb/blob/0cbb56d14cc1464d945a06cb8bac051485fa2ef7/test/sql/aggregate/group/test_group_by.test#L151-L156).

Repro with test data:

```
$ cat integers.sup
{i:3(int32),j:4(int32)}
{i:3(int32),j:4(int32)}
{i:2(int32),j:4(int32)}

$ super -version
Version: 944989687

$ super -c "SELECT i % 2 AS k, SUM(i) FROM 'integers.sup' GROUP BY k, k ORDER BY 1;"
{k:1,"SUM(i)":6}
{k:0,"SUM(i)":2}
```

Whereas in Postgres, it looks like the `ORDER BY` had the intended effect.

```
$ psql postgres
psql (17.5 (Homebrew))
Type "help" for help.

postgres=# SELECT * FROM integers;
 i | j 
---+---
 3 | 4
 3 | 4
 2 | 4
(3 rows)

postgres=# SELECT i % 2 AS k, SUM(i) FROM integers GROUP BY k, k ORDER BY 1;
 k | sum 
---+-----
 0 |   2
 1 |   6
(2 rows)
```

### LINKED ISSUE #5976: SQL: Output not stable with ORDER BY column number on GROUP BY'd aggregation
Repro is with super commit 9449896. This was found via a query from [a sqllogictest](https://github.com/duckdb/duckdb/blob/0cbb56d14cc1464d945a06cb8bac051485fa2ef7/test/sql/aggregate/group/test_group_by.test#L167-L174).

With the following input data `integers2.sup`:

```
{i:1(int32)}
{i:2(int32)}
{i:3(int32)}
{i:null(int32)}
```

The output of the following query differs in repeated runs with `super`.

```
$ super -version
Version: 944989687

$ super -c "SELECT i, SUM(i) FROM 'integers2.sup' GROUP BY i ORDER BY 1;"
{i:1(int32),"SUM(i)":1}
{i:2(int32),"SUM(i)":2}
{i:3(int32),"SUM(i)":3}
{i:null(int32),"SUM(i)":null(int64)}

$ super -c "SELECT i, SUM(i) FROM 'integers2.sup' GROUP BY i ORDER BY 1;"
{i:3(int32),"SUM(i)":3}
{i:null(int32),"SUM(i)":null(int64)}
{i:1(int32),"SUM(i)":1}
{i:2(int32),"SUM(i)":2}
```

However, if the SQL ends with a reference to the column by name via `ORDER BY i` the output is stable.

In Postgres, the output against a table with the same input data is stable with both `ORDER BY 1` and `ORDER BY i`.

### PR DESCRIPTION
**Pull request by mattnibs**
Closes #5976
Closes #5948
Closes #5975

### CODE REVIEW

File: compiler/semantic/schema.go [hunk 1]
```diff
@@ -173,6 +176,62 @@ func (j *joinUsingSchema) resolveColumn(col string) (field.Path, error) {
...
+	case *dag.This:
+		return &dag.This{Kind: "This", Path: append([]string{path}, e.Path...)}
+	case *dag.IndexExpr:
+		return &dag.IndexExpr{
+			Kind:  "IndexExpr",
+			Expr:  appendExprToPath(path, e.Expr),
+			Index: e.Index,
+		}
+	default:
+		panic("hi")
```
Comment (mccanne) [inline compiler/semantic/schema.go]: Either change "hi" to "appendExprToPath" or better just assert e.(*dag.This) without the type switch or "ok" and you will get a reasonable panic for something that shouldn't hapen.

**Review by mccanne — APPROVED** [review]
Neat!

File: compiler/semantic/schema.go (hunk 1 above)
Comment (mattnibs) [reply compiler/semantic/schema.go]: whoops!
