### PR TITLE
Handle vector.Const time arg in vam/expr/function.DatePart fast path

### LINKED ISSUE #5842: "panic: (*vector.Const)" in vector runtime query against ~1-billion values
## tl;dr

```
$ super -version
Version: v1.18.0-426-g196d094e7

$ SUPER_VAM=1 super -c "
SELECT
    commit.collection AS event,
    EXTRACT(HOUR FROM time(time_us*1000)) as hour_of_day,
    count() AS count
FROM 'bluesky-196d094.csup'
WHERE kind = 'commit'
  AND commit.operation = 'create'
  AND commit.collection in ['app.bsky.feed.post', 'app.bsky.feed.repost', 'app.bsky.feed.like']
GROUP BY event, hour_of_day
ORDER BY hour_of_day, event;"
panic: (*vector.Const) 0xc0024da320

goroutine 15 [running]:
github.com/brimdata/super/runtime/vam/expr/function.date_time_hour({0x23a4a50?, 0xc0024da320?})
        /home/ubuntu/super/runtime/vam/expr/function/datepartfuncs.go:107 +0x2d3
github.com/brimdata/super/runtime/vam/expr/function.(*DatePart).Call(0xc00042c100, {0xc00095c460, 0x2, 0x479285?})
        /home/ubuntu/super/runtime/vam/expr/function/datepart.go:32 +0x1f4
github.com/brimdata/super/vector.Apply(0x8?, 0x2?, {0xc00095c460?, 0xc0036322c0?, 0x1e9d000?})
        /home/ubuntu/super/vector/apply.go:17 +0xa3
github.com/brimdata/super/vector.Apply(0x1, 0xc001cd1d60, {0xc000113aa0?, 0xc001cd1d68?, 0xc000359b80?})
        /home/ubuntu/super/vector/apply.go:23 +0x10e
github.com/brimdata/super/runtime/vam/expr.(*Call).Eval(0xc0005f94f0, {0x23a45a0, 0xc003632040})
        /home/ubuntu/super/runtime/vam/expr/eval.go:39 +0xf4
github.com/brimdata/super/runtime/vam/op/aggregate.(*Aggregate).Pull(0xc0004891e0, 0x0?)
        /home/ubuntu/super/runtime/vam/op/aggregate/aggregate.go:72 +0x41a
github.com/brimdata/super/runtime/vam/op.(*combineParent).run(0xc0007aef40)
        /home/ubuntu/super/runtime/vam/op/combine.go:110 +0x3c
created by github.com/brimdata/super/runtime/vam/op.(*Combine).Pull.func1 in goroutine 12
        /home/ubuntu/super/runtime/vam/op/combine.go:42 +0x35
```

## Details

Repro is with super commit 196d094 and a CSUP file made from a cleaned up copy of the ~1-billion Bluesky events in the JSONBench data set.

This problem doesn't trigger with any of the sets of 100-million events at a time. Thankfully @nwt has eyeballed the stack trace and thinks he sees a fix, so I'll plan to test out a branch on my AWS instance where I have the full CSUP data file ready to go.

### PR DESCRIPTION
**Pull request by nwt**
Fixes #5842.

### CODE REVIEW

File: runtime/vam/expr/function/gendatepartfuncs.go [hunk 1]
```diff
@@ -32,16 +32,20 @@ case *vector.View:
 	out := make([]int64, len(index))
 	for i, idx := range index {
 		v := inner.Values[idx]
-		out[i] = %s
+		out[i] = %[1]s
```
Comment (nwt) [inline runtime/vam/expr/function/gendatepartfuncs.go:35]: See https://pkg.go.dev/fmt#hdr-Explicit_argument_indexes for details on this %[1]s business.

**Comment by philrz** [comment]
Fix looks good from here! No more panic. 👍

```
$ super -version
Version: v1.18.0-429-g565a9d057

$ SUPER_VAM=1 super -c "
SELECT
    commit.collection AS event,
    EXTRACT(HOUR FROM time(time_us*1000)) as hour_of_day,
    count() AS count
FROM 'bluesky-196d094.csup'
WHERE kind = 'commit'
  AND commit.operation = 'create'
  AND commit.collection in ['app.bsky.feed.post', 'app.bsky.feed.repost', 'app.bsky.feed.like']
GROUP BY event, hour_of_day
ORDER BY hour_of_day, event;"

{event:"app.bsky.feed.like",hour_of_day:0,count:22284576(uint64)}
{event:"app.bsky.feed.post",hour_of_day:0,count:4020629(uint64)}
{event:"app.bsky.feed.repost",hour_of_day:0,count:2757179(uint64)}
{event:"app.bsky.feed.like",hour_of_day:1,count:22909742(uint64)}
{event:"app.bsky.feed.post",hour_of_day:1,count:4133628(uint64)}
{event:"app.bsky.feed.repost",hour_of_day:1,count:2800662(uint64)}
...
```

**Review by mattnibs — APPROVED** [review]
