### PR TITLE
vam: Fix filters on true bool values marked null

### LINKED ISSUE #5679: Incorrect query result in vector runtime aggregation on multi-step generated CSUP
## tl;dr

Given the `WHERE` clause, the top line of output in the following aggregation result is incorrect.

```
$ SUPER_VAM=1 super -c "SELECT SearchPhrase, COUNT(*) AS c FROM 'bench0.csup' WHERE SearchPhrase <> '' GROUP BY SearchPhrase ORDER BY c DESC LIMIT 10;"
{SearchPhrase:"",c:4016547(uint64)}
{SearchPhrase:"карелки",c:70263(uint64)}
{SearchPhrase:"албатрутдин",c:34675(uint64)}
{SearchPhrase:"смотреть онлайн",c:24580(uint64)}
{SearchPhrase:"смотреть онлайн бесплатно",c:21647(uint64)}
{SearchPhrase:"смотреть",c:19707(uint64)}
{SearchPhrase:"мангу в зарабей грама",c:19195(uint64)}
{SearchPhrase:"дружке помещение",c:17284(uint64)}
{SearchPhrase:"galaxy table",c:16746(uint64)}
{SearchPhrase:"экзоидные",c:16620(uint64)}
```

## Details

Repro is with super commit 2f1a964. This is the [ClickBench q12 query](https://github.com/ClickHouse/ClickBench/blob/a2b51e3bf21e6e8c1987f8846e4d530aa62ba6ba/duckdb/queries.sql#L13).

For reasons unrelated to this particular issue (but that ended up surfacing this issue anyway) I happened to be generating my CSUP test data from the original [hits CSV](https://datasets.clickhouse.com/hits_compatible/hits.csv.gz) in multiple steps:

1. First loaded it into DuckDB as a table created with DDL [`ddl_duckdb.sql`](https://github.com/brimdata/mgbench-private/blob/clickbench/bench0/ddl/ddl_duckdb.sql)
2. Then dumped it out of the DuckDB table as a Parquet file
3. Then turned that Parquet file into CSUP.

Here I'll show those steps while issuing a query along the way to see the presumed correct result when querying the DuckDB table.

```
$ duckdb --version
v1.1.3 19864453f7

$ duckdb q12.db < ddl_duckdb.sql 

$ duckdb q12.db -c "COPY bench0 FROM 'hits.csv'"
100% ▕████████████████████████████████████████████████████████████▏ 

$ duckdb q12.db -c "SELECT SearchPhrase, COUNT(*) AS c FROM bench0 WHERE SearchPhrase <> '' GROUP BY SearchPhrase ORDER BY c DESC LIMIT 10;"
┌───────────────────────────┬───────┐
│       SearchPhrase        │   c   │
│          varchar          │ int64 │
├───────────────────────────┼───────┤
│ карелки                   │ 70263 │
│ албатрутдин               │ 34675 │
│ смотреть онлайн           │ 24580 │
│ смотреть онлайн бесплатно │ 21647 │
│ смотреть                  │ 19707 │
│ мангу в зарабей грама     │ 19195 │
│ дружке помещение          │ 17284 │
│ galaxy table              │ 16746 │
│ экзоидные                 │ 16620 │
│ сколько мытищи            │ 12317 │
├───────────────────────────┴───────┤
│ 10 rows                 2 columns │
└───────────────────────────────────┘

$ duckdb q12.db -c "COPY (FROM bench0) TO 'bench0.parquet'"
100% ▕████████████████████████████████████████████████████████████▏ 

$ super -version
Version: v1.18.0-302-g2f1a9643

$ super -f csup -o bench0.csup bench0.parquet
```

At this point if we issue the same query we did in DuckDB _in sequential runtime_ against the CSUP file, our result matches the one from DuckDB.

```
$ super -c "SELECT SearchPhrase, COUNT(*) AS c FROM 'bench0.csup' WHERE SearchPhrase <> '' GROUP BY SearchPhrase ORDER BY c DESC LIMIT 10;"
{SearchPhrase:"карелки",c:70263(uint64)}
{SearchPhrase:"албатрутдин",c:34675(uint64)}
{SearchPhrase:"смотреть онлайн",c:24580(uint64)}
{SearchPhrase:"смотреть онлайн бесплатно",c:21647(uint64)}
{SearchPhrase:"смотреть",c:19707(uint64)}
{SearchPhrase:"мангу в зарабей грама",c:19195(uint64)}
{SearchPhrase:"дружке помещение",c:17284(uint64)}
{SearchPhrase:"galaxy table",c:16746(uint64)}
{SearchPhrase:"экзоидные",c:16620(uint64)}
{SearchPhrase:"сколько мытищи",c:12317(uint64)}
```

However, once we repeat it in vector runtime, now we get that first row that includes a count for `SearchPhrase:""` which should have been excluded per the `WHERE` clause.

```
$ SUPER_VAM=1 super -c "SELECT SearchPhrase, COUNT(*) AS c FROM 'bench0.csup' WHERE SearchPhrase <> '' GROUP BY SearchPhrase ORDER BY c DESC LIMIT 10;"
{SearchPhrase:"",c:4016547(uint64)}
{SearchPhrase:"карелки",c:70263(uint64)}
{SearchPhrase:"албатрутдин",c:34675(uint64)}
{SearchPhrase:"смотреть онлайн",c:24580(uint64)}
{SearchPhrase:"смотреть онлайн бесплатно",c:21647(uint64)}
{SearchPhrase:"смотреть",c:19707(uint64)}
{SearchPhrase:"мангу в зарабей грама",c:19195(uint64)}
{SearchPhrase:"дружке помещение",c:17284(uint64)}
{SearchPhrase:"galaxy table",c:16746(uint64)}
{SearchPhrase:"экзоидные",c:16620(uint64)}
```

### PR DESCRIPTION
**Pull request by mattnibs**
This commit fixes an issue with filters in the vector runtime where boolean vectors where null values that were also set to true were not getting filtered as they should.

Closes #5679

### CODE REVIEW

File: runtime/vam/expr/conditional.go [hunk 1]
```diff
@@ -103,17 +103,23 @@ func boolMaskRidx(ridx []uint32, bools, errs *roaring.Bitmap, vec vector.Any) {
 		}
 	case *vector.Bool:
 		if ridx != nil {
+			trues := vec
+			if vec.Nulls != nil {
+				// if null and true set to false
+				trues = vector.And(trues, vector.Not(vec.Nulls))
+			}
```
Comment (nwt) [inline runtime/vam/expr/conditional.go:110]: You've added this same code to both branches of this if statement. Just add once copy of it before the if.
```suggestion
		trues := vec
		if vec.Nulls != nil {
			// if null and true set to false
			trues = vector.And(trues, vector.Not(vec.Nulls))
		}
		if ridx != nil {
```

**Review by nwt — APPROVED** [review]
