### PR TITLE
vam: Fix nested cuts / puts

### LINKED ISSUE #5741: Cut on multiple nested fields in vector runtime
There's a bug in vector runtime when doing a cut on multiple nested fields sharing the same root path:
```
$ echo {rec:{a:1,b:2}} | SUPER_VAM=1 super -c 'cut rec.a,rec.b' -
```

This should return the original record but it instead returns `{rec:{b:2}}`

### PR DESCRIPTION
**Pull request by mattnibs**
Closes #5741

### CODE REVIEW

File: compiler/kernel/vop.go [hunk 1]
```diff
@@ -302,27 +303,31 @@ func (b *Builder) compileVamLeaf(o dag.Op, parent vector.Puller) (vector.Puller,
...
+		addPathToRecord(rec, lhs.Path, a.RHS)
 	}
-	return b.compileVamRecordExpr(&dag.RecordExpr{Kind: "RecordExpr", Elems: elems})
+	return b.compileVamRecordExpr(rec)
 }
 
-func newDagRecordExprForPath(path []string, expr dag.Expr) *dag.RecordExpr {
-	if len(path) > 1 {
-		expr = newDagRecordExprForPath(path[1:], expr)
+func addPathToRecord(rec *dag.RecordExpr, path []string, expr dag.Expr) {
```
Comment (nwt) [inline compiler/kernel/vop.go:317]:
```suggestion
func addPathToRecordExpr(rec *dag.RecordExpr, path []string, expr dag.Expr) {
```

**Review by nwt — APPROVED** [review]
:shipit:
