### PR TITLE
Dedupe inferred column names in SQL Selects

### LINKED ISSUE #5862: Duplicated aggregation produces only one result
## tl;dr

Given input `data.json`:

```
{"n": 1}
{"n": 2}
```

The single `sum` result shown below is unexpected, since in other SQL systems all three aggregation results are returned.

```
$ SUPER_VAM=1 super -c "SELECT SUM(n), SUM(n+1), SUM(n+2) FROM data.json;"
{sum:7}
```

## Details

Repro is with super commit 2231fd9. This is a simplification of the [ClickBench query 29](https://github.com/ClickHouse/ClickBench/blob/8440f516891d7b75563e895f9bd2a1b413d38970/duckdb/queries.sql#L30).

Perhaps the result is an unsurprising side effect of our not yet having support for columns with duplicate names? FWIW, if I add `AS` to each aggregation to assign unique column names, it works as expected.

```
$ super -version
Version: v1.18.0-445-g2231fd961

$ SUPER_VAM=1 super -c "SELECT SUM(n) AS n_0, SUM(n+1) AS n_1, SUM(n+2) AS n_2 FROM data.json;"
{n_0:3,n_1:5,n_2:7}
```

That said, other SQL systems just create unique column names in this situation. Examples:

```
$ duckdb -c "SELECT SUM(n), SUM(n+1), SUM(n+2) FROM data.json;"
┌────────┬──────────────┬──────────────┐
│ sum(n) │ sum((n + 1)) │ sum((n + 2)) │
│ int128 │    int128    │    int128    │
├────────┼──────────────┼──────────────┤
│   3    │      5       │      7       │
└────────┴──────────────┴──────────────┘

$ clickhouse --output-format TabSeparatedWithNames --query "SELECT SUM(n), SUM(n+1), SUM(n+2) FROM 'data.json';"
SUM(n)	SUM(plus(n, 1))	SUM(plus(n, 2))
3	5	7
```

Whereas in SuperDB"s vector runtime as shown above it looks like only the "rightmost" aggregation result is preserved.

FWIW, in sequential runtime, it's a panic instead.

```
$ super -c "SELECT SUM(n), SUM(n+1), SUM(n+2) FROM data.json;"
panic: duplicate field: "sum"
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:26 +0x5e
github.com/brimdata/super/runtime/sam/op.(*Catcher).Pull.func1()
	/Users/phil/work/super/runtime/sam/op/catcher.go:25 +0x3d
panic({0x97bc860?, 0xc0004a4320?})
	/usr/local/opt/go/libexec/src/runtime/panic.go:792 +0x132
github.com/brimdata/super.(*Context).MustLookupTypeRecord(...)
	/Users/phil/work/super/context.go:179
github.com/brimdata/super/runtime/sam/expr.(*recordExpr).Eval(0xc0006157c0, {0x51bf7360, 0xc0000a6d50}, {{0x9a8ca60?, 0xc0000a6cc0?}, 0xc0004ae918?, 0x20?})
	/Users/phil/work/super/runtime/sam/expr/values.go:60 +0x3b3
github.com/brimdata/super/runtime/sam/op/yield.(*Op).Pull(0xc00047e840, 0x0)
	/Users/phil/work/super/runtime/sam/op/yield/yield.go:34 +0x42b
github.com/brimdata/super/runtime/sam/op.(*Single).Pull(0xc0000a6ae0, 0x5?)
	/Users/phil/work/super/runtime/sam/op/mux.go:120 +0x33
github.com/brimdata/super/runtime/sam/op.(*Catcher).Pull(0x4e62d91f42a2d62a?, 0x39?)
	/Users/phil/work/super/runtime/sam/op/catcher.go:28 +0x5c
github.com/brimdata/super/runtime/exec.(*Query).Pull(0x7adf0df?, 0x60?)
	/Users/phil/work/super/runtime/exec/query.go:49 +0x3c
github.com/brimdata/super/zbuf.CopyMux(0xc00059fca8, {0x9a83a00, 0xc0000a6b10})
	/Users/phil/work/super/zbuf/mux.go:40 +0x38
github.com/brimdata/super/cmd/super/root.(*Command).Run(0xc00042e600, {0xc00003c710, 0x0, 0x0})
	/Users/phil/work/super/cmd/super/root/command.go:167 +0x925
github.com/brimdata/super/pkg/charm.path.run({0xc000080c08, 0x1, 0x1}, {0xc00003c710, 0x0, 0x0?})
	/Users/phil/work/super/pkg/charm/path.go:11 +0x7b
github.com/brimdata/super/pkg/charm.(*Spec).Exec(0xabd2f20, {0xc00003c700, 0x2, 0x2})
	/Users/phil/work/super/pkg/charm/charm.go:71 +0x105
main.main()
	/Users/phil/work/super/cmd/super/main.go:40 +0x5b
```

And in vector runtime, this changed as of the merge of #5669. Before that, there also was an error message in vector runtime. As of the commit right before then:

```
$ super -version
Version: v1.18.0-293-g0f8e7dbef

$ SUPER_VAM=1 super -c "SELECT SUM(n), SUM(n+1), SUM(n+2) FROM data.json;"
duplicate field: "sum"
```

### PR DESCRIPTION
**Pull request by mattnibs**
Closes #5862

### CODE REVIEW

File: compiler/semantic/sql.go [hunk 1]
```diff
@@ -533,29 +534,53 @@ func (a *analyzer) semGroupBy(sch *selectSchema, in []ast.Expr) []exprloc {
...
 			}
-			a.error(n, fmt.Errorf("%q: conflicting name in projection; try an AS clause", col.name))
+			aliases[col.name] = struct{}{}
 		}
-		conflict[col.name] = struct{}{}
 		proj = append(proj, *col)
+	}
+	// Do we have duplicates for inferred columns? If an alias and an
+	// inferred column collide the inferred name should be changed.
+	conflict := maps.Clone(aliases)
```
Comment (nwt) [inline compiler/semantic/sql.go:556]: Is this necessary?

Comment (mattnibs) [reply compiler/semantic/sql.go:556]: The maps.Clone is not necessary and I was going to get rid of this. The name change made the code more readable to me but am willing to get rid of that as well.

Comment (mattnibs) [reply compiler/semantic/sql.go]: I got rid of it

**Review by nwt — APPROVED** [review]
